type: filestream
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
tail_files: true
recursive_glob.enabled: true
symlinks: false
include_lines: ["^[I|W|E|F][[:digit:]]{4}?"]
multiline:
  pattern: '"^[I|W|E|F][[:digit:]]{4}?"'
  match: after
tags: ["impala", "statestored"]
processors:
  - impala_log:
      field: "message"
      overwrite_keys: true
      ignore_missing: false
      ignore_failure: false
