// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package impala

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "impala", asset.ModuleFieldsPri, AssetImpala); err != nil {
		panic(err)
	}
}

// AssetImpala returns asset data.
// This is the base64 encoded zlib format compressed contents of module/impala.
func AssetImpala() string {
	return "eJxsTrFqxTAM3P0Vh+dm6+ShWymFln5CMLGamMq2iJXSUPrvRXl58IZ3i3R36HQDvmgPyEUiRwdoVqYA/3oI3gGJ+rRm0dxqwJMDgIuJ95Y2Jgd8ZuLUw+ENqLHQTaJBd6GAeW2bnMqdVMPz4/j28RLw6zUX6hqL+Af4pXW1GUU4T9GujE6tSKtUD4/bPDJ9ExvRZaWYRqtilH6UarKt9Nn/ne+utf8DAAD//46cTc8="
}
